In [1]:
import pandas as pd
import numpy as np

In [2]:
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
category_map = pd.read_csv("product_category_name_translation.csv")
# importing all the datasets

In [3]:
orders.shape

(99441, 8)

In [4]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [5]:
orders.isna().sum()
# we can find null values in 3 columns ("order_approved_at",'order_delivered_carrier_date','order_delivered_customer_date')

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

#Understanding the Data

In [6]:
orders['order_status'].value_counts(normalize=True)*100
# we can see the percentage of orders in different stages
# we can see a total of ~1.2% of the orders are cancelled /unavailable which shows the origin of losses

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [7]:
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col], errors='coerce')
    # converting the object fields to date time.

In [8]:
orders['delivery_delay_days']=(orders['order_delivered_customer_date']-orders['order_estimated_delivery_date']).dt.days

In [9]:
orders['delivery_delay_days'].describe()
# we can see an average of 12 days to deliver a package and even went up to 188days at the Max

count    96476.000000
mean       -11.876881
std         10.183854
min       -147.000000
25%        -17.000000
50%        -12.000000
75%         -7.000000
max        188.000000
Name: delivery_delay_days, dtype: float64

In [10]:
# when delay in delivery increases the reviews gradually go Down

In [11]:
orders_reviews = orders.merge(
    reviews[['order_id', 'review_score']],
    on='order_id',
    how='left'
)

orders_reviews.groupby('review_score')['delivery_delay_days'].mean()

review_score
1.0    -4.060580
2.0    -8.634818
3.0   -10.774052
4.0   -12.380840
5.0   -13.388153
Name: delivery_delay_days, dtype: float64

In [12]:
# As per result it is completely opposite ,so lets check for the delayed data

In [13]:
late_orders = orders_reviews[orders_reviews['delivery_delay_days'] > 0]

late_orders.groupby('review_score')['delivery_delay_days'].mean()

review_score
1.0    12.360337
2.0    10.233813
3.0     9.058739
4.0     8.414110
5.0     6.989623
Name: delivery_delay_days, dtype: float64

In [14]:
# it is confirmed that when the delay goes up the reviews goes down

In [15]:
customer_order_counts=orders.groupby('customer_id')['order_id'].count()
customer_order_counts.value_counts().head(10)

order_id
1    99441
Name: count, dtype: int64

In [16]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [17]:
orders_customers = orders.merge(
    customers[['customer_id', 'customer_unique_id']],on='customer_id',how='left')

In [18]:
customer_order_counts = orders_customers.groupby('customer_unique_id')['order_id'].count()
customer_order_counts.value_counts().head(10)

order_id
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [19]:
order_items[['seller_id','product_id']].nunique()
# we can see that there are 3095 sellers and 32951 unique products

seller_id      3095
product_id    32951
dtype: int64

# Feature Engineering

In [20]:
orders['delivery_delay_days']=(orders['order_delivered_customer_date']-orders['order_estimated_delivery_date']).dt.days
# we are finding the no of delayed delivery days

In [21]:
orders['is_late_delivery']=orders['delivery_delay_days']>0
# creating a new categorical cloumn that tells if it is a delayed delivery or not

In [22]:
orders['is_late_delivery'].value_counts()
# we can see a total of 6535 delayed deliveries

is_late_delivery
False    92906
True      6535
Name: count, dtype: int64

In [23]:
orders['is_late_delivery'].mean()*100
# 6.57% of deliveries are delayed

np.float64(6.571736004263835)

In [24]:
order_revenue = payments.groupby('order_id')['payment_value'].sum().reset_index()
# we are segmenting the revenue per order
orders = orders.merge(order_revenue, on='order_id', how='left')
# merging the payment_value of each order from the order_revenue dataframe

In [25]:
order_revenue.head()
# Dataframe that contains the payment_value for each order

                           order_id  payment_value
0  00010242fe8c5a6d1ba2dd792cb16214          72.19
1  00018f77f2f0320c557190d7a144bdd3         259.83
2  000229ec398224ef6ca0657da4fc703e         216.87
3  00024acbcdf0a6daa1e931b038114c75          25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9         218.04

In [26]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,is_late_delivery,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,False,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,False,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,False,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13.0,False,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10.0,False,28.62

In [27]:
orders['payment_value'].describe()

count    99440.000000
mean       160.990267
std        221.951257
min          0.000000
25%         62.010000
50%        105.290000
75%        176.970000
max      13664.080000
Name: payment_value, dtype: float64

In [28]:
latest_date = orders['order_purchase_timestamp'].max()

last_order = orders.groupby('customer_id')['order_purchase_timestamp'].max()

customer_features = pd.DataFrame({
    'last_order_date': last_order
})

customer_features['days_since_last_order'] = (
    latest_date - customer_features['last_order_date']
).dt.days

customer_features['churn_flag'] = customer_features['days_since_last_order'] > 90
# we are assuming the a customer has churned if the difference between the current date and 
# last order is more than 90 days.

In [29]:
customer_features['churn_flag'].mean()*100
# churn Percentage.

np.float64(90.15597188282499)

In [30]:
orders = orders.merge(
    customer_features[['churn_flag']],
    left_on='customer_id',
    right_index=True,
    how='left'
)
# we are merging the churn_flag with the orders table using the customer_id.

In [31]:
orders = orders.merge(
    reviews[['order_id', 'review_score']],
    on='order_id',
    how='left'
)
# we are mergig the review_score in the order table to identify the score per order.

In [32]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,is_late_delivery,payment_value,churn_flag,review_score
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,False,38.71,True,4.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,False,141.46,False,4.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,False,179.12,False,5.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13.0,False,72.20,True,5.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10.0,False,28.62,True,5.0

In [33]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99992 entries, 0 to 99991
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99992 non-null  object
 1   customer_id                    99992 non-null  object
 2   order_status                   99992 non-null  object
 3   order_purchase_timestamp       99992 non-null  datetime64[ns]
 4   order_approved_at              99831 non-null  datetime64[ns]
 5   order_delivered_carrier_date   98199 non-null  object
 6   order_delivered_customer_date  97005 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99992 non-null  datetime64[ns]
 8   delivery_delay_days            97005 non-null  float64
 9   is_late_delivery               99992 non-null  bool
 10  payment_value                  99991 non-null  float64
 11  churn_flag                     99992 non-null  bool
 12  review_score                   99224 non-null  float64
dtypes: bool(2), datetime64[ns](4), float64(3), object(4)
memory usage: 8.6+ MB

# BUSINESS INTELLIGENCE METRICS

In [34]:
orders['revenue_at_risk'] = (
    (orders['is_late_delivery']) |
    (orders['review_score'] <= 2) |
    (orders['churn_flag'])
)

In [35]:
risk_revenue = orders.loc[
    orders['revenue_at_risk'], 'payment_value'
].sum()

total_revenue = orders['payment_value'].sum()

risk_percentage = (risk_revenue / total_revenue) * 100

risk_percentage

np.float64(91.84044033661668)

In [36]:
# 91.84% of revenue is threatened by poor operations

In [37]:
churn_rate = orders['churn_flag'].mean() * 100
churn_rate

np.float64(90.19721577726219)

In [38]:
# 90.1% of customers never return

In [39]:
orders.groupby('is_late_delivery')['review_score'].mean()

is_late_delivery
False    4.211789
True     2.271139
Name: review_score, dtype: float64

In [40]:
# scores when deliver is delayed vs delivery is on time

In [41]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99992 entries, 0 to 99991
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99992 non-null  object
 1   customer_id                    99992 non-null  object
 2   order_status                   99992 non-null  object
 3   order_purchase_timestamp       99992 non-null  datetime64[ns]
 4   order_approved_at              99831 non-null  datetime64[ns]
 5   order_delivered_carrier_date   98199 non-null  object
 6   order_delivered_customer_date  97005 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99992 non-null  datetime64[ns]
 8   delivery_delay_days            97005 non-null  float64
 9   is_late_delivery               99992 non-null  bool
 10  payment_value                  99991 non-null  float64
 11  churn_flag                     99992 non-null  bool
 12  review_score                   99224 non-null  float64
 13  revenue_at_risk                99992 non-null  bool
dtypes: bool(3), datetime64[ns](4), float64(3), object(4)
memory usage: 8.7+ MB

In [42]:
orders_sellers = orders.merge(
    order_items[['order_id', 'seller_id']],
    on='order_id',
    how='left'
)
# we are merging to to score the sellers based on the deliveriers

In [43]:
seller_risk = orders_sellers.groupby('seller_id').agg({
    'delivery_delay_days': 'mean',
    'review_score': 'mean',
    'payment_value': 'sum'
}).reset_index()
# getting an avg scores(delivery days,review_score,payment valuse) for the sellers - to find the worst sellers

In [44]:
seller_risk.sort_values(
    ['delivery_delay_days', 'review_score'],
    ascending=[False, True]
).head(10)

,seller_id,delivery_delay_days,review_score,payment_value
2699,df683dfda87bf71ac3fc63063fba369d,167.000000,1.000000,55.95
1745,8e670472e453ba34a379331513d6aab1,35.000000,1.000000,1083.96
1645,8629a7efec1aab257e58cda559f03ba7,33.000000,1.000000,64.11
958,4fb41dff7c50136976d1a5cf004a42e2,33.000000,4.000000,1296.77
2884,eebb3372362aa9a46975164bed19a7e7,27.000000,2.285714,889.84
2711,e09887ca8c7bf8a4621ce481820414ef,24.333333,3.000000,261.54
667,391bbd13b6452244774beff1824006ed,24.000000,1.000000,163.20
2292,be1e9e378700cecaa4ebf71433d7915c,23.500000,3.000000,157.51
1079,586a871d4f1221763fddb6ceefdeb95e,22.000000,1.000000,478.96
793,427165bf50f8ca07efc7bdc2bfcf1688,17.800000,3.200000,1692.90

In [45]:
seller_risk = seller_risk.rename(columns={
    'delivery_delay_days': 'avg_delivery_delay',
    'review_score': 'avg_review_score',
    'payment_value': 'total_revenue'
})
# RENAMING THE COLUMNS

In [46]:
seller_risk.head()

,seller_id,avg_delivery_delay,avg_review_score,total_revenue
0,0015a82c2db000af6aaaf3ae2ecb0532,-16.333333,3.666667,2748.06
1,001cca7ae9ae17fb1caed9dfb1094831,-13.213675,3.902542,48349.22
2,001e6ad469a905060d959994f1b41e4f,NaN,1.000000,267.94
3,002100f778ceb8431b7a1020ff7ab48f,-8.218182,3.982143,2478.33
4,003554e2dce176b5555353e4f3555ac8,-27.000000,5.000000,139.38

In [47]:
seller_risk['seller_risk_score'] = (
    seller_risk['avg_delivery_delay'] * 0.6
    + (5 - seller_risk['avg_review_score']) * 0.4
)
# Reviews are from 1–5
#(5 - review_score) converts low reviews into higher risk.

In [48]:
seller_risk = seller_risk.sort_values(
    'seller_risk_score',
    ascending=False
)
# Identifying the worst sellers.

In [49]:
seller_risk.head(10)
# Top 10 worstsellers

,seller_id,avg_delivery_delay,avg_review_score,total_revenue,seller_risk_score
2699,df683dfda87bf71ac3fc63063fba369d,167.000000,1.000000,55.95,101.800000
1745,8e670472e453ba34a379331513d6aab1,35.000000,1.000000,1083.96,22.600000
1645,8629a7efec1aab257e58cda559f03ba7,33.000000,1.000000,64.11,21.400000
958,4fb41dff7c50136976d1a5cf004a42e2,33.000000,4.000000,1296.77,20.200000
2884,eebb3372362aa9a46975164bed19a7e7,27.000000,2.285714,889.84,17.285714
667,391bbd13b6452244774beff1824006ed,24.000000,1.000000,163.20,16.000000
2711,e09887ca8c7bf8a4621ce481820414ef,24.333333,3.000000,261.54,15.400000
2292,be1e9e378700cecaa4ebf71433d7915c,23.500000,3.000000,157.51,14.900000
1079,586a871d4f1221763fddb6ceefdeb95e,22.000000,1.000000,478.96,14.800000
495,2a50b7ee5aebecc6fd0ff9784a4747d6,17.000000,1.000000,528.48,11.800000

In [50]:
seller_risk.describe()

       avg_delivery_delay  avg_review_score  total_revenue  seller_risk_score
count         2970.000000       3090.000000    3095.000000        2967.000000
mean           -12.287906          3.973340    6596.718107          -7.014615
std              7.999842          0.970685   21698.226870           4.870178
min            -66.000000          1.000000      12.220000         -38.533333
25%            -15.448661          3.712470     320.500000          -9.000000
50%            -12.000000          4.166667    1255.710000          -6.840000
75%             -9.000000          4.604632    4884.675000          -5.123109
max            167.000000          5.000000  512645.190000         101.800000

In [51]:
revenue_at_risk = orders.loc[
    orders['revenue_at_risk'], 'payment_value'
].sum()

total_revenue = orders['payment_value'].sum()

risk_percentage = (revenue_at_risk / total_revenue) * 100

print(risk_percentage)

91.84044033661668

In [52]:
# Shows the revenue at risk

In [53]:
from sqlalchemy import create_engine

In [54]:
import sys
!{sys.executable} -m pip install pymysql

Requirement already satisfied: pymysql in /opt/homebrew/anaconda3/lib/python3.13/site-packages (1.1.2)

In [57]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root1234@localhost:3306/olist_db"
)

In [58]:
engine.connect()

In [59]:
customers[['customer_id','customer_city','customer_state']].drop_duplicates().to_sql(
    'dim_customers',
    engine,
    if_exists='replace',
    index=False
)

99441

In [60]:
sellers[['seller_id','seller_city','seller_state']].drop_duplicates().to_sql(
    'dim_sellers',
    engine,
    if_exists='replace',
    index=False
)

3095

In [61]:
products[['product_id','product_category_name']].drop_duplicates().to_sql(
    'dim_products',
    engine,
    if_exists='replace',
    index=False
)

32951

In [62]:
orders.to_sql(
    'fact_orders',
    engine,
    if_exists='replace',
    index=False
)

99992

In [63]:
orders_with_sellers = orders.merge(
    order_items[['order_id','seller_id','product_id']],
    on='order_id',
    how='left'
)

In [64]:
orders_with_sellers.to_sql(
    'fact_orders',
    engine,
    if_exists='replace',
    index=False
)

114092